name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Run-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run test
      run: |
        pytest

  Sonar-scan:
    runs-on: ubuntu-latest
    needs: Run-test

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: SonarCloud Scanning
      uses: sonarsource/sonarcloud-github-action@v2.3.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Trivy-Fs-scan:
    runs-on: ubuntu-latest
    needs: Sonar-scan
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner 
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-report.sarif'
        severity: 'HIGH,CRITICAL'

    - name: Upload Trivy report to Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-report.sarif'

  Build-and-push-Docker-image:
    runs-on: ubuntu-latest
    needs: Trivy-Fs-scan

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }} 

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          testingkyaw/my-python-app:latest
          testingkyaw/my-python-app:${{ github.sha }}
