name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Run-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run test
      run: |
        pytest

  Sonar-scan:
    runs-on: ubuntu-latest
    needs: Run-test

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: SonarCloud Scanning
      uses: sonarsource/sonarcloud-github-action@v2.3.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Trivy-Fs-scan:
    runs-on: ubuntu-latest
    needs: Sonar-scan
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner 
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-report.sarif'
        severity: 'HIGH,CRITICAL'

    - name: Display Trivy report
      run: cat trivy-report.sarif

    - name: Upload Trivy report to Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-report.sarif'

  Build-image:
    runs-on: ubuntu-latest
    needs: Trivy-Fs-scan

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: build docker image
      run: |
        docker build -t testingkyaw/my-python-app:latest .
        docker save -o vuln-image.tar testingkyaw/my-python-app:latest
        pwd
        ls -lrta

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: vuln-image
          path: /github/workspace/vuln-image.tar

  Trivy-Container-image-scan:
    runs-on: ubuntu-latest
    needs: Build-image

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: vuln-image
        path: /github/workspace

    - name: Run Trivy vulnerability scanner in tarball mode
      uses: aquasecurity/trivy-action@0.20.0
      with:
        input: /github/workspace/vuln-image.tar
        severity: 'CRITICAL,HIGH'
